stages:
  - build_ami

build_ami:
  stage: build_ami
  image: hashicorp/packer:latest
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  script:
    - packer build aws-ami-v1.pkr.hcl
